### ISSUE TITLE
User roles & authorization logic

### ISSUE THREAD

**Issue by zflat** [bikebike/BikeBike#19]
I see that there is a column in the users table caled 'role' of type string. I did a search in the repo and I don't see any code using this column, unless I am missing something.

Is there anything that is defining the roles & how they are being used? Assigning roles to a user will be a good way to handle authorization and other application logic. If we expect to have complex authorization logic, then we may need users to be able to have multiple roles. So having a string may not be enough for us. 

So my other question is, how are we planning on using roles, what roles will we need to define?

**Comment by G0dwin** [comment]
Going forward we do need at least 2 roles:

- **administrator**: A user that is given access to edit conferences without being a member of a host organization
- **translator**: once we have a site up that can be used to translate, this will be used to let users translate and email them when their translations change

We should rename this to `role_id` and create a `role` model so that we can easily add more than one role to a user and look up users by role later.
